from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from typing import Any

from .utils import hash64


@dataclass(slots=True)
class Generation:
    trace: str
    answer: int
    tool_code: str | None


class BaseGeneratorModel:
    """Interface for candidate generation models."""

    def generate(self, prompt: str, *, seed: int, max_tokens: int, temperature: float) -> Generation:
        raise NotImplementedError


class StrictModelRequirementError(RuntimeError):
    """Raised when mandatory GPT-OSS-120B requirement is not satisfied."""


class DeterministicHeuristicModel(BaseGeneratorModel):
    """Deterministic test double; not used in default runtime."""

    def generate(self, prompt: str, *, seed: int, max_tokens: int, temperature: float) -> Generation:
        base = hash64(f"{prompt}|{seed}|{max_tokens}|{temperature}")
        answer = int(base % 100000)
        trace = (
            "Structured reasoning path generated by deterministic heuristic model. "
            "Use only for tests/dev overrides."
        )
        tool_code = (
            "from fractions import Fraction\n"
            f"ANSWER = {answer}\n"
        )
        return Generation(trace=trace, answer=answer, tool_code=tool_code)


class GPTOSS120BModel(BaseGeneratorModel):
    """Mandatory production generator built on openai/gpt-oss-120b."""

    MODEL_ID = "openai/gpt-oss-120b"

    def __init__(
        self,
        *,
        model_id: str = MODEL_ID,
        model_path: str | None = None,
        backend: str | None = None,
        gpu_memory_utilization: float = 0.90,
        max_model_len: int = 8192,
    ) -> None:
        self.model_id = model_id
        self.model_path = model_path or os.getenv("AIMO3_MODEL_PATH", model_id)
        self.backend = (backend or os.getenv("AIMO3_LLM_BACKEND", "vllm")).strip().lower()
        self.gpu_memory_utilization = gpu_memory_utilization
        self.max_model_len = max_model_len

        self._loaded = False
        self._llm: Any = None
        self._sampling_params_cls: Any = None
        self._tokenizer: Any = None
        self._model: Any = None

    def _ensure_loaded(self) -> None:
        if self._loaded:
            return

        if self.model_id != self.MODEL_ID:
            raise StrictModelRequirementError(
                f"Model bắt buộc là '{self.MODEL_ID}', hiện tại nhận '{self.model_id}'."
            )

        if self.backend == "vllm":
            try:
                from vllm import LLM, SamplingParams  # type: ignore
            except Exception as exc:  # pragma: no cover
                raise StrictModelRequirementError(
                    "Không import được vLLM. Cài vllm hoặc đổi AIMO3_LLM_BACKEND=transformers."
                ) from exc

            self._llm = LLM(
                model=self.model_path,
                trust_remote_code=True,
                gpu_memory_utilization=self.gpu_memory_utilization,
                max_model_len=self.max_model_len,
                tensor_parallel_size=int(os.getenv("AIMO3_TP", "1")),
                seed=0,
            )
            self._sampling_params_cls = SamplingParams
            self._loaded = True
            return

        if self.backend == "transformers":
            try:
                import torch  # type: ignore
                from transformers import AutoModelForCausalLM, AutoTokenizer  # type: ignore
            except Exception as exc:  # pragma: no cover
                raise StrictModelRequirementError(
                    "Không import được transformers/torch. Cài dependencies inference để chạy GPT-OSS-120B."
                ) from exc

            self._tokenizer = AutoTokenizer.from_pretrained(self.model_path, trust_remote_code=True)
            self._model = AutoModelForCausalLM.from_pretrained(
                self.model_path,
                trust_remote_code=True,
                torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
                device_map="auto",
            )
            self._loaded = True
            return

        raise StrictModelRequirementError(
            "AIMO3_LLM_BACKEND phải là 'vllm' hoặc 'transformers'."
        )

    def generate(self, prompt: str, *, seed: int, max_tokens: int, temperature: float) -> Generation:
        self._ensure_loaded()
        formatted_prompt = self._format_prompt(prompt)
        raw = self._generate_raw(formatted_prompt, seed=seed, max_tokens=max_tokens, temperature=temperature)
        return self._parse_generation(raw)

    def _generate_raw(self, prompt: str, *, seed: int, max_tokens: int, temperature: float) -> str:
        if self.backend == "vllm":
            sp = self._sampling_params_cls(
                temperature=max(0.0, float(temperature)),
                top_p=0.95 if temperature > 0 else 1.0,
                max_tokens=max(32, int(max_tokens)),
                seed=int(seed),
            )
            outs = self._llm.generate([prompt], sp, use_tqdm=False)
            if not outs or not outs[0].outputs:
                return ""
            return str(outs[0].outputs[0].text)

        # transformers backend
        import torch  # type: ignore

        tok = self._tokenizer(prompt, return_tensors="pt")
        tok = {k: v.to(self._model.device) for k, v in tok.items()}
        with torch.no_grad():
            out_ids = self._model.generate(
                **tok,
                do_sample=bool(temperature > 0),
                temperature=max(float(temperature), 1e-5),
                top_p=0.95,
                max_new_tokens=max(32, int(max_tokens)),
            )
        new_ids = out_ids[0][tok["input_ids"].shape[1]:]
        return str(self._tokenizer.decode(new_ids, skip_special_tokens=True))

    def _format_prompt(self, prompt: str) -> str:
        return (
            "You are solving an olympiad-style math problem. "
            "Return ONLY JSON with keys: answer (int), trace (short string), tool_code (python string or null).\n"
            f"Problem:\n{prompt}\n"
        )

    def _parse_generation(self, text: str) -> Generation:
        obj = _extract_best_json(text)
        if obj is not None:
            answer = _coerce_int(obj.get("answer"))
            trace = str(obj.get("trace") or obj.get("reasoning") or "")
            tool_code = obj.get("tool_code")
            if tool_code is not None:
                tool_code = str(tool_code)
            return Generation(
                trace=trace.strip() or "no-trace",
                answer=answer % 100000,
                tool_code=tool_code,
            )

        answer = _extract_fallback_answer(text)
        trace = text.strip()[:1200] if text else "no-trace"
        return Generation(trace=trace, answer=answer % 100000, tool_code=None)


class BaseJudgeModel:
    def score(self, problem: str, trace: str, answer: int, artifacts: dict) -> float:
        raise NotImplementedError


class DeterministicJudge(BaseJudgeModel):
    def score(self, problem: str, trace: str, answer: int, artifacts: dict) -> float:
        del trace
        signal = 0.2
        if "sandbox" in artifacts:
            signal += 0.3
        if "mod" in problem.lower():
            signal += 0.1
        signal += (answer % 7) / 20.0
        return max(0.0, min(signal, 0.99))


def load_required_gpt_oss_120b() -> GPTOSS120BModel:
    model_id = os.getenv("AIMO3_MODEL_ID", GPTOSS120BModel.MODEL_ID)
    if model_id != GPTOSS120BModel.MODEL_ID:
        raise StrictModelRequirementError(
            f"Cấu hình sai: AIMO3_MODEL_ID phải là '{GPTOSS120BModel.MODEL_ID}'."
        )
    model_path = os.getenv("AIMO3_MODEL_PATH", model_id)
    backend = os.getenv("AIMO3_LLM_BACKEND", "vllm")
    return GPTOSS120BModel(model_id=model_id, model_path=model_path, backend=backend)


def _extract_best_json(text: str) -> dict[str, Any] | None:
    decoder = json.JSONDecoder()
    best: dict[str, Any] | None = None
    i = 0
    while i < len(text):
        if text[i] != "{":
            i += 1
            continue
        try:
            obj, n = decoder.raw_decode(text[i:])
            if isinstance(obj, dict):
                best = obj
                if "answer" in obj:
                    return obj
            i += max(n, 1)
        except Exception:
            i += 1
    return best


def _extract_fallback_answer(text: str) -> int:
    boxed = re.findall(r"\\\\boxed\{\s*(-?\d+)\s*\}", text)
    if boxed:
        return int(boxed[-1])

    finals = re.findall(r"FINAL\s*:\s*(-?\d+)", text, flags=re.IGNORECASE)
    if finals:
        return int(finals[-1])

    ints = re.findall(r"-?\d+", text)
    if ints:
        return int(ints[-1])
    return 0


def _coerce_int(v: Any) -> int:
    if isinstance(v, bool):
        return int(v)
    if isinstance(v, int):
        return v
    if isinstance(v, float):
        return int(v)
    if isinstance(v, str):
        m = re.search(r"-?\d+", v)
        if m:
            return int(m.group(0))
    return 0

